{
 "title": "DOM DG",
 "tags": [ "vsan" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "DOM DG IOPS (Read)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_domdg_io_total{disk_role=\"cache\",io_type=\"read\"}[1m])) by (hostname, disk_uuid,io_type)"
    }
   ]
  },
  {
   "title": "DOM DG IOPS (Write)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_domdg_io_total{disk_role=\"cache\",io_type=\"write\"}[1m])) by (hostname, disk_uuid,io_type)"
    }
   ]
  },
  {
   "title": "DOM DG Tput (Read)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "format": "Bps",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_domdg_io_bytes_total{disk_role=\"cache\",io_type=\"read\"}[1m])) by (hostname, disk_uuid,io_type)"
    }
   ]
  },
  {
   "title": "DOM DG Tput (Write)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "format": "Bps",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_domdg_io_bytes_total{disk_role=\"cache\",io_type=\"write\"}[1m])) by (hostname, disk_uuid,io_type)"
    }
   ]
  },
  {
   "title": "DOM DG Avg IO Size (Read)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "format": "bytes",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_domdg_io_bytes_total{disk_role=\"cache\",io_type=\"read\"}[1m])) by (hostname, disk_uuid,io_type) / sum(rate(vmware_vsan_domdg_io_total{disk_role=\"cache\",io_type=\"read\"}[1m]) +1) by (hostname, disk_uuid,io_type)"
    }
   ]
  },
  {
   "title": "DOM DG Avg IO Size (Write)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "format": "bytes",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_domdg_io_bytes_total{disk_role=\"cache\",io_type=\"write\"}[1m])) by (hostname, disk_uuid,io_type) / sum(rate(vmware_vsan_domdg_io_total{disk_role=\"cache\",io_type=\"write\"}[1m]) +1) by (hostname, disk_uuid,io_type)"
    }
   ]
  },
  {
   "title": "DOM DG Latency (Read)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "format": "s",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_domdg_io_duration_seconds_total{disk_role=\"cache\",io_type=\"read\"}[1m])) by (hostname, disk_uuid,io_type) / sum(rate(vmware_vsan_domdg_io_total{disk_role=\"cache\",io_type=\"read\"}[1m]) +1) by (hostname, disk_uuid,io_type)"
    }
   ]
  },
  {
   "title": "DOM DG Latency (Write)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "format": "s",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_domdg_io_duration_seconds_total{disk_role=\"cache\",io_type=\"write\"}[1m])) by (hostname, disk_uuid,io_type) / sum(rate(vmware_vsan_domdg_io_total{disk_role=\"cache\",io_type=\"write\"}[1m]) +1) by (hostname, disk_uuid,io_type)"
    }
   ]
  },
  {
   "title": "DOM DG Outstanding IO (QD) (Read)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_domdg_numoio_total{disk_role=\"cache\",io_type=\"read\"}[1m])) by (hostname, disk_uuid,io_type) / sum(rate(vmware_vsan_domdg_io_total{disk_role=\"cache\",io_type=\"read\"}[1m]) +1) by (hostname, disk_uuid,io_type)"
    }
   ]
  },
  {
   "title": "DOM DG Outstanding IO (QD) (Write)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_domdg_numoio_total{disk_role=\"cache\",io_type=\"write\"}[1m])) by (hostname, disk_uuid,io_type) / sum(rate(vmware_vsan_domdg_io_total{disk_role=\"cache\",io_type=\"write\"}[1m]) +1) by (hostname, disk_uuid,io_type)"
    }
   ]
  },
  {
   "title": "Write Buffer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "format": "percentunit",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(vmware_vsan_disk_writebuffer_usage_bytes{disk_role=\"cache\"}) by (hostname, disk_uuid) / sum(vmware_vsan_disk_writebuffer_size_bytes{disk_role=\"cache\"}) by (hostname, disk_uuid)"
    }
   ]
  },
  {
   "title": "WB Drain/Destage Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "format": "Bps",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(vmware_vsan_disk_drain_bytes_total{disk_role=\"cache\"}[1m])"
    }
   ]
  },
  {
   "title": "Congestion (0-255)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vmware_vsan_disk_congestion_total{disk_role=\"cache\"}) by (hostname, disk_uuid, congestion_type)"
    }
   ]
  },
  {
   "title": "Congestion (Tput based)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "format": "Bps",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(vmware_vsan_disk_congestion_bytespersecond{disk_role=\"cache\"}) by (hostname, disk_uuid)"
    }
   ]
  }
 ]
}