{
 "title": "vSAN Direct Host",
 "tags": [ "vsan" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "vSAN Direct Latency (Read)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "format": "s",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_disks_dev_duration_seconds_total{storagepool=~\"storagepool-vsandirect.*\",io_type=\"read\"}[1m])) by (hostname, io_type) / sum(rate(vmware_vsan_disks_dev_io_total{storagepool=~\"storagepool-vsandirect.*\", io_type=\"read\"}[1m])) by (hostname, io_type)"
    }
   ]
  },
  {
   "title": "vSAN Direct Latency (Write)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "format": "s",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_disks_dev_duration_seconds_total{storagepool=~\"storagepool-vsandirect.*\",io_type=\"write\"}[1m])) by (hostname, io_type) / sum(rate(vmware_vsan_disks_dev_io_total{storagepool=~\"storagepool-vsandirect.*\", io_type=\"write\"}[1m])) by (hostname, io_type)"
    }
   ]
  },
  {
   "title": "vSAN Direct IOPS (Read)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_disks_dev_io_total{storagepool=~\"storagepool-vsandirect.*\",io_type=\"read\"}[1m])) by (hostname, io_type)"
    }
   ]
  },
  {
   "title": "vSAN Direct IOPS (Write)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_disks_dev_io_total{storagepool=~\"storagepool-vsandirect.*\",io_type=\"write\"}[1m])) by (hostname, io_type)"
    }
   ]
  },
  {
   "title": "vSAN Direct Tput (Read)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 160 },
   "format": "Bps",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_disks_dev_bytes_total{storagepool=~\"storagepool-vsandirect.*\",io_type=\"read\"}[1m])) by (hostname, io_type)"
    }
   ]
  },
  {
   "title": "vSAN Direct Tput (Write)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 160 },
   "format": "Bps",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_disks_dev_bytes_total{storagepool=~\"storagepool-vsandirect.*\",io_type=\"write\"}[1m])) by (hostname, io_type)"
    }
   ]
  }
 ]
}