{
 "title": "vSAN Layers",
 "tags": [ "vsan" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "DOM Client Latency (Read)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "format": "s",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_dom_io_duration_seconds_total{role=\"client\", io_type=\"read\"}[1m])) by (hostname, io_type, role) / sum(rate(vmware_vsan_dom_io_total{role=\"client\", io_type=\"read\"}[1m]) +1) by (hostname, io_type, role)"
    }
   ]
  },
  {
   "title": "DOM Client Latency (Write)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "format": "s",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_dom_io_duration_seconds_total{role=\"client\", io_type=\"write\"}[1m])) by (hostname, io_type, role) / sum(rate(vmware_vsan_dom_io_total{role=\"client\", io_type=\"write\"}[1m]) +1) by (hostname, io_type, role)"
    }
   ]
  },
  {
   "title": "DOM Owner Latency (Read)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "format": "s",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_dom_io_duration_seconds_total{role=\"owner\", io_type=\"read\"}[1m])) by (hostname, io_type, role) / sum(rate(vmware_vsan_dom_io_total{role=\"owner\", io_type=\"read\"}[1m]) +1) by (hostname, io_type, role)"
    }
   ]
  },
  {
   "title": "DOM Owner Latency (Write)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "format": "s",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_dom_io_duration_seconds_total{role=\"owner\", io_type=\"write\"}[1m])) by (hostname, io_type, role) / sum(rate(vmware_vsan_dom_io_total{role=\"owner\", io_type=\"write\"}[1m]) +1) by (hostname, io_type, role)"
    }
   ]
  },
  {
   "title": "DOM Owner Leaf Latency (Read)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "format": "s",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_dom_io_duration_seconds_total{role=\"ownerLeaf\", io_type=\"read\"}[1m])) by (hostname, io_type, role) / sum(rate(vmware_vsan_dom_io_total{role=\"ownerLeaf\", io_type=\"read\"}[1m]) +1) by (hostname, io_type, role)"
    }
   ]
  },
  {
   "title": "DOM Owner Leaf Latency (Write)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "format": "s",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_dom_io_duration_seconds_total{role=\"ownerLeaf\", io_type=\"write\"}[1m])) by (hostname, io_type, role) / sum(rate(vmware_vsan_dom_io_total{role=\"ownerLeaf\", io_type=\"write\"}[1m]) +1) by (hostname, io_type, role)"
    }
   ]
  },
  {
   "title": "DOM CompMgr Latency (Read)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "format": "s",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_dom_io_duration_seconds_total{role=\"compmgr\", io_type=\"read\"}[1m])) by (hostname, io_type, role) / sum(rate(vmware_vsan_dom_io_total{role=\"compmgr\", io_type=\"read\"}[1m]) +1) by (hostname, io_type, role)"
    }
   ]
  },
  {
   "title": "DOM CompMgr Latency (Write)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "format": "s",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_dom_io_duration_seconds_total{role=\"compmgr\", io_type=\"write\"}[1m])) by (hostname, io_type, role) / sum(rate(vmware_vsan_dom_io_total{role=\"compmgr\", io_type=\"write\"}[1m]) +1) by (hostname, io_type, role)"
    }
   ]
  },
  {
   "title": "DOM CompMgr DG Latency (Read)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "format": "s",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_domdg_io_duration_seconds_total{disk_role=\"cache\",io_type=\"read\"}[1m])) by (hostname, disk_uuid, io_type) / sum(rate(vmware_vsan_domdg_io_total{disk_role=\"cache\", io_type=\"read\"}[1m]) +1) by (hostname, disk_uuid, io_type)"
    }
   ]
  },
  {
   "title": "DOM CompMgr DG Latency (Write)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "format": "s",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_domdg_io_duration_seconds_total{disk_role=\"cache\",io_type=\"write\"}[1m])) by (hostname, disk_uuid, io_type) / sum(rate(vmware_vsan_domdg_io_total{disk_role=\"cache\", io_type=\"write\"}[1m]) +1) by (hostname, disk_uuid, io_type)"
    }
   ]
  },
  {
   "title": "LSOM Cache Latency (Read)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "format": "s",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_disks_dev_duration_seconds_total{disk_role=\"cache\",io_type=\"read\"}[1m])) by (hostname, disk_uuid, io_type) / sum(rate(vmware_vsan_disks_dev_io_total{disk_role=\"cache\", io_type=\"read\"}[1m]) +1) by (hostname, disk_uuid, io_type)"
    }
   ]
  },
  {
   "title": "LSOM Cache Latency (Write)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "format": "s",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_disks_dev_duration_seconds_total{disk_role=\"cache\",io_type=\"write\"}[1m])) by (hostname, disk_uuid, io_type) / sum(rate(vmware_vsan_disks_dev_io_total{disk_role=\"cache\", io_type=\"write\"}[1m]) +1) by (hostname, disk_uuid, io_type)"
    }
   ]
  },
  {
   "title": "LSOM Capacity Latency (Read)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "format": "s",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_disks_dev_duration_seconds_total{disk_role=\"capacity\",io_type=\"read\"}[1m])) by (hostname, disk_uuid, io_type) / sum(rate(vmware_vsan_disks_dev_io_total{disk_role=\"capacity\", io_type=\"read\"}[1m]) +1) by (hostname, disk_uuid, io_type)"
    }
   ]
  },
  {
   "title": "LSOM Capacity Latency (Write)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "format": "s",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_disks_dev_duration_seconds_total{disk_role=\"capacity\",io_type=\"write\"}[1m])) by (hostname, disk_uuid, io_type) / sum(rate(vmware_vsan_disks_dev_io_total{disk_role=\"capacity\", io_type=\"write\"}[1m]) +1) by (hostname, disk_uuid, io_type)"
    }
   ]
  },
  {
   "title": "DOM Client IOPS (Read)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_dom_io_total{role=\"client\", io_type=\"read\"}[1m])) by (hostname, io_type, role)"
    }
   ]
  },
  {
   "title": "DOM Client IOPS (Write)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_dom_io_total{role=\"client\", io_type=\"write\"}[1m])) by (hostname, io_type, role)"
    }
   ]
  },
  {
   "title": "DOM Owner IOPS (Read)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_dom_io_total{role=\"owner\", io_type=\"read\"}[1m])) by (hostname, io_type, role)"
    }
   ]
  },
  {
   "title": "DOM Owner IOPS (Write)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_dom_io_total{role=\"owner\", io_type=\"write\"}[1m])) by (hostname, io_type, role)"
    }
   ]
  },
  {
   "title": "DOM Owner Leaf IOPS (Read)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_dom_io_total{role=\"ownerLeaf\", io_type=\"read\"}[1m])) by (hostname, io_type, role)"
    }
   ]
  },
  {
   "title": "DOM Owner Leaf IOPS (Write)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_dom_io_total{role=\"ownerLeaf\", io_type=\"write\"}[1m])) by (hostname, io_type, role)"
    }
   ]
  },
  {
   "title": "DOM CompMgr IOPS (Read)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_dom_io_total{role=\"compmgr\", io_type=\"read\"}[1m])) by (hostname, io_type, role)"
    }
   ]
  },
  {
   "title": "DOM CompMgr IOPS (Write)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_dom_io_total{role=\"compmgr\", io_type=\"write\"}[1m])) by (hostname, io_type, role)"
    }
   ]
  },
  {
   "title": "DOM CompMgr DG IOPS (Read)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_domdg_io_total{disk_role=\"cache\",io_type=\"read\"}[1m])) by (hostname, disk_uuid, io_type)"
    }
   ]
  },
  {
   "title": "DOM CompMgr DG IOPS (Write)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_domdg_io_total{disk_role=\"cache\",io_type=\"write\"}[1m])) by (hostname, disk_uuid, io_type)"
    }
   ]
  },
  {
   "title": "LSOM Cache IOPS (Read)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_disks_dev_io_total{disk_role=\"cache\",io_type=\"read\"}[1m])) by (hostname, disk_uuid, io_type)"
    }
   ]
  },
  {
   "title": "LSOM Cache IOPS (Write)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_disks_dev_io_total{disk_role=\"cache\",io_type=\"write\"}[1m])) by (hostname, disk_uuid, io_type)"
    }
   ]
  },
  {
   "title": "LSOM Capacity IOPS (Read)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_disks_dev_io_total{disk_role=\"capacity\",io_type=\"read\"}[1m])) by (hostname, disk_uuid, io_type)"
    }
   ]
  },
  {
   "title": "LSOM Capacity IOPS (Write)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_disks_dev_io_total{disk_role=\"capacity\",io_type=\"write\"}[1m])) by (hostname, disk_uuid, io_type)"
    }
   ]
  },
  {
   "title": "DOM Client Tput (Read)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "format": "Bps",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_dom_io_bytes_total{role=\"client\", io_type=\"read\"}[1m])) by (hostname, io_type, role)"
    }
   ]
  },
  {
   "title": "DOM Client Tput (Write)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "format": "Bps",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_dom_io_bytes_total{role=\"client\", io_type=\"write\"}[1m])) by (hostname, io_type, role)"
    }
   ]
  },
  {
   "title": "DOM Owner Tput (Read)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "format": "Bps",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_dom_io_bytes_total{role=\"owner\", io_type=\"read\"}[1m])) by (hostname, io_type, role)"
    }
   ]
  },
  {
   "title": "DOM Owner Tput (Write)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
   "format": "Bps",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_dom_io_bytes_total{role=\"owner\", io_type=\"write\"}[1m])) by (hostname, io_type, role)"
    }
   ]
  },
  {
   "title": "DOM CompMgr Tput (Read)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
   "format": "Bps",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_dom_io_bytes_total{role=\"compmgr\", io_type=\"read\"}[1m])) by (hostname, io_type, role)"
    }
   ]
  },
  {
   "title": "DOM CompMgr Tput (Write)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 128 },
   "format": "Bps",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_dom_io_bytes_total{role=\"compmgr\", io_type=\"write\"}[1m])) by (hostname, io_type, role)"
    }
   ]
  },
  {
   "title": "DOM CompMgr DG Tput (Read)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 136 },
   "format": "Bps",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_domdg_io_bytes_total{disk_role=\"cache\",io_type=\"read\"}[1m])) by (hostname, disk_uuid, io_type)"
    }
   ]
  },
  {
   "title": "DOM CompMgr DG Tput (Write)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 136 },
   "format": "Bps",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_domdg_io_bytes_total{disk_role=\"cache\",io_type=\"write\"}[1m])) by (hostname, disk_uuid, io_type)"
    }
   ]
  },
  {
   "title": "LSOM Cache Tput (Read)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 144 },
   "format": "Bps",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_disks_dev_bytes_total{disk_role=\"cache\",io_type=\"read\"}[1m])) by (hostname, disk_uuid, io_type)"
    }
   ]
  },
  {
   "title": "LSOM Cache Tput (Write)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 144 },
   "format": "Bps",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_disks_dev_bytes_total{disk_role=\"cache\",io_type=\"write\"}[1m])) by (hostname, disk_uuid, io_type)"
    }
   ]
  },
  {
   "title": "LSOM Capacity Tput (Read)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 152 },
   "format": "Bps",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_disks_dev_bytes_total{disk_role=\"capacity\",io_type=\"read\"}[1m])) by (hostname, disk_uuid, io_type)"
    }
   ]
  },
  {
   "title": "LSOM Capacity Tput (Write)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 152 },
   "format": "Bps",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_disks_dev_bytes_total{disk_role=\"capacity\",io_type=\"write\"}[1m])) by (hostname, disk_uuid, io_type)"
    }
   ]
  },
  {
   "title": "DOM Client OIO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 168 },
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_dom_numoio_total{role=\"client\"}[1m])) by (hostname, role) / sum(rate(vmware_vsan_dom_io_total{role=\"client\"}[1m]) +1) by (hostname, role)"
    }
   ]
  },
  {
   "title": "DOM Owner OIO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 176 },
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_dom_numoio_total{role=\"owner\"}[1m])) by (hostname, role) / sum(rate(vmware_vsan_dom_io_total{role=\"owner\"}[1m]) +1) by (hostname, role)"
    }
   ]
  },
  {
   "title": "DOM CompMgr OIO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 184 },
   "format": "short",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_dom_numoio_total{role=\"compmgr\"}[1m])) by (hostname, role) / sum(rate(vmware_vsan_dom_io_total{role=\"compmgr\"}[1m]) +1) by (hostname, role)"
    }
   ]
  }
 ]
}