{
 "title": "vSAN CPU",
 "tags": [ "vsan" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "DOM Top-5 CPU Utilization (Usage)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "format": "percent",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(5, rate(vmware_esx_world_usedtime_seconds_total{subsystem=\"DOM\"}[1m]) / rate(vmware_esx_world_uptime_seconds_total{subsystem=\"DOM\"}[1m])) * 100"
    }
   ]
  },
  {
   "title": "DOM Top-5 CPU Utilization (Ready)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "format": "percent",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(5, rate(vmware_esx_world_readytime_seconds_total{subsystem=\"DOM\"}[1m]) / rate(vmware_esx_world_uptime_seconds_total{subsystem=\"DOM\"}[1m])) * 100"
    }
   ]
  },
  {
   "title": "LLOG Top-5 CPU Utilization (Usage)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "format": "percent",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(5, rate(vmware_esx_world_usedtime_seconds_total{subsystem=\"LLOG\"}[1m]) / rate(vmware_esx_world_uptime_seconds_total{subsystem=\"LLOG\"}[1m])) * 100"
    }
   ]
  },
  {
   "title": "LLOG Top-5 CPU Utilization (Ready)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "format": "percent",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(5, rate(vmware_esx_world_readytime_seconds_total{subsystem=\"LLOG\"}[1m]) / rate(vmware_esx_world_uptime_seconds_total{subsystem=\"LLOG\"}[1m])) * 100"
    }
   ]
  },
  {
   "title": "PLOG Top-5 CPU Utilization (Usage)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "format": "percent",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(5, rate(vmware_esx_world_usedtime_seconds_total{subsystem=\"PLOG\"}[1m]) / rate(vmware_esx_world_uptime_seconds_total{subsystem=\"PLOG\"}[1m])) * 100"
    }
   ]
  },
  {
   "title": "PLOG Top-5 CPU Utilization (Ready)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "format": "percent",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(5, rate(vmware_esx_world_readytime_seconds_total{subsystem=\"PLOG\"}[1m]) / rate(vmware_esx_world_uptime_seconds_total{subsystem=\"PLOG\"}[1m])) * 100"
    }
   ]
  },
  {
   "title": "Network Top-5 CPU Utilization (Usage)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "format": "percent",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(5, rate(vmware_esx_world_usedtime_seconds_total{subsystem=\"Network\"}[1m]) / rate(vmware_esx_world_uptime_seconds_total{subsystem=\"Network\"}[1m])) * 100"
    }
   ]
  },
  {
   "title": "Network Top-5 CPU Utilization (Ready)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "format": "percent",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(5, rate(vmware_esx_world_readytime_seconds_total{subsystem=\"Network\"}[1m]) / rate(vmware_esx_world_uptime_seconds_total{subsystem=\"Network\"}[1m])) * 100"
    }
   ]
  },
  {
   "title": "CMMDS Top-5 CPU Utilization (Usage)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "format": "percent",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(5, rate(vmware_esx_world_usedtime_seconds_total{subsystem=\"CMMDS\"}[1m]) / rate(vmware_esx_world_uptime_seconds_total{subsystem=\"CMMDS\"}[1m])) * 100"
    }
   ]
  },
  {
   "title": "CMMDS Top-5 CPU Utilization (Ready)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "format": "percent",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(5, rate(vmware_esx_world_readytime_seconds_total{subsystem=\"CMMDS\"}[1m]) / rate(vmware_esx_world_uptime_seconds_total{subsystem=\"CMMDS\"}[1m])) * 100"
    }
   ]
  }
 ]
}