{
 "title": "Basic vSAN Dashboard",
 "tags": [ "vsan" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Mongo PVC Latency (read)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_vscsi_io_duration_seconds_total{cns_k8s_pvc_name=~\".*mongo.*\",io_type=\"read\"}[1m])) by (cns_k8s_pvc_name) / sum(rate(vmware_vsan_vscsi_io_total{cns_k8s_pvc_name=~\".*mongo.*\",io_type=\"read\"}[1m])) by (cns_k8s_pvc_name)"
    }
   ]
  },
  {
   "title": "Mongo PVC Latency (write)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_vscsi_io_duration_seconds_total{cns_k8s_pvc_name=~\".*mongo.*\",io_type=\"write\"}[1m])) by (cns_k8s_pvc_name) / sum(rate(vmware_vsan_vscsi_io_total{cns_k8s_pvc_name=~\".*mongo.*\",io_type=\"write\"}[1m])) by (cns_k8s_pvc_name)"
    }
   ]
  },
  {
   "title": "Mongo PVC IOPS (read)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_vscsi_io_total{cns_k8s_pvc_name=~\".*mongo.*\",io_type=\"read\"}[1m])) by (cns_k8s_pvc_name)"
    }
   ]
  },
  {
   "title": "Mongo PVC IOPS (write)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_vscsi_io_total{cns_k8s_pvc_name=~\".*mongo.*\",io_type=\"write\"}[1m])) by (cns_k8s_pvc_name)"
    }
   ]
  },
  {
   "title": "Mongo PVC Tput (read)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_vscsi_io_bytes_total{cns_k8s_pvc_name=~\".*mongo.*\",io_type=\"read\"}[1m])) by (cns_k8s_pvc_name)"
    }
   ]
  },
  {
   "title": "Mongo PVC Tput (write)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_vscsi_io_bytes_total{cns_k8s_pvc_name=~\".*mongo.*\",io_type=\"write\"}[1m])) by (cns_k8s_pvc_name)"
    }
   ]
  },
  {
   "title": "DOM DG IOPS (Read)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_domdg_io_total{disk_role=\"cache\",io_type=\"read\"}[1m])) by (hostname, disk_uuid,io_type)"
    }
   ]
  },
  {
   "title": "DOM DG IOPS (write)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_domdg_io_total{disk_role=\"cache\",io_type=\"write\"}[1m])) by (hostname, disk_uuid,io_type)"
    }
   ]
  },
  {
   "title": "DOM DG Tput (read)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_domdg_io_bytes_total{disk_role=\"cache\",io_type=\"read\"}[1m])) by (hostname, disk_uuid,io_type)"
    }
   ]
  },
  {
   "title": "DOM DG Tput (write)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vmware_vsan_domdg_io_bytes_total{disk_role=\"cache\",io_type=\"write\"}[1m])) by (hostname, disk_uuid,io_type)"
    }
   ]
  },
  {
   "title": "Write Buffer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "percentunit", "label": "Fill Percent" }
   ],
   "targets": [
    {
     "expr": "sum(vmware_vsan_disk_writebuffer_usage_bytes{disk_role=\"cache\"}) by (hostname, disk_uuid) / sum(vmware_vsan_disk_writebuffer_size_bytes{disk_role=\"cache\"}) by (hostname, disk_uuid)"
    }
   ]
  },
  {
   "title": "WB Drain/Destage Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "Bps", "label": "Drain Rate" }
   ],
   "targets": [
    {
     "expr": "rate(vmware_vsan_disk_drain_bytes_total{disk_role=\"cache\"}[1m])"
    }
   ]
  },
  {
   "title": "Congestion (Tput based)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(vmware_vsan_disk_congestion_bytespersecond{disk_role=\"cache\"}) by (hostname, disk_uuid)"
    }
   ]
  },
  {
   "title": "Congestion (0-255)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vmware_vsan_disk_congestion_total{disk_role=\"cache\"}) by (hostname, disk_uuid, congestion_type)"
    }
   ]
  }
 ]
}